/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import logic.Kontroler;
import model.ModelTabeleProdavci;
import server.NitKlijenta;
import server.PokretanjeServera;


public class FormaServer extends javax.swing.JFrame {

    /**
     * Creates new form FormaServer
     */
    List<NitKlijenta> listaKlijenata;
    PokretanjeServera ps;
    
    public FormaServer() {
        try {
            initComponents();
            
            srediTabelu(new ArrayList<>());
            srediPrikaz();
            Kontroler.getInstance().setForma(this);
        } catch (Exception ex) {
            Logger.getLogger(FormaServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblPokreniServer = new javax.swing.JLabel();
        jbtnPokreniServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUlogovaniKorisnici = new javax.swing.JTable();
        jbtnZaustaviServer = new javax.swing.JButton();
        jbtnKonfiguracijaParametara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        jlblPokreniServer.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblPokreniServer.setForeground(new java.awt.Color(255, 0, 0));
        jlblPokreniServer.setText("SERVER NIJE POKRENUT!");

        jbtnPokreniServer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPokreniServer.setText("Pokreni server");
        jbtnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPokreniServerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel1.setText("Lista ulogovanih korisnika:");

        jtblUlogovaniKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblUlogovaniKorisnici);

        jbtnZaustaviServer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnZaustaviServer.setText("Zaustavi server");
        jbtnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZaustaviServerActionPerformed(evt);
            }
        });

        jbtnKonfiguracijaParametara.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnKonfiguracijaParametara.setText("Konfiguracija parametara baze");
        jbtnKonfiguracijaParametara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKonfiguracijaParametaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnKonfiguracijaParametara)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblPokreniServer)
                                        .addGap(139, 139, 139)
                                        .addComponent(jbtnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(jbtnZaustaviServer)))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnKonfiguracijaParametara, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPokreniServer)
                    .addComponent(jbtnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPokreniServerActionPerformed
       ps = new PokretanjeServera();
    ps.start();
    jlblPokreniServer.setText("SERVER JE POKRENUT!");
    jlblPokreniServer.setForeground(Color.BLUE);
    jbtnPokreniServer.setVisible(false);
    jbtnZaustaviServer.setVisible(true);
    }//GEN-LAST:event_jbtnPokreniServerActionPerformed

    private void jbtnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZaustaviServerActionPerformed
    int odgovor = JOptionPane.showConfirmDialog(this, 
         "Da li ste sigurni da želite da zaustavite server?",
         "Potvrda gašenja", 
         JOptionPane.YES_NO_OPTION);

     if (odgovor == JOptionPane.YES_OPTION) {
         try {
             if (ps != null) {
                 ps.zaustaviServer();
             }

             jlblPokreniServer.setText("SERVER NIJE POKRENUT!");
             jlblPokreniServer.setForeground(Color.RED);
             jbtnPokreniServer.setVisible(true);
             jbtnZaustaviServer.setVisible(false);

             // Obriši tabelu ulogovanih
             ModelTabeleProdavci model = (ModelTabeleProdavci) jtblUlogovaniKorisnici.getModel();
             model.postaviListu(new ArrayList<>());

             JOptionPane.showMessageDialog(this, "Server je uspešno zaustavljen.");

         } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Greška pri gašenju servera: " + ex.getMessage());
         }
     }
    }//GEN-LAST:event_jbtnZaustaviServerActionPerformed

    private void jbtnKonfiguracijaParametaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKonfiguracijaParametaraActionPerformed
         FormaKonfiguracijaBaze fkb = new FormaKonfiguracijaBaze();
        fkb.setVisible(true);
    }//GEN-LAST:event_jbtnKonfiguracijaParametaraActionPerformed

//    /**
//     * @param args the command line arguments
//     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnKonfiguracijaParametara;
    private javax.swing.JButton jbtnPokreniServer;
    private javax.swing.JButton jbtnZaustaviServer;
    private javax.swing.JLabel jlblPokreniServer;
    private javax.swing.JTable jtblUlogovaniKorisnici;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu(ArrayList<OpstiDomenskiObjekat> listaProdavaca) {
    ModelTabeleProdavci mtp = new ModelTabeleProdavci(listaProdavaca);
    jtblUlogovaniKorisnici.setModel(mtp);
    jtblUlogovaniKorisnici.setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    jtblUlogovaniKorisnici.getTableHeader().setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    
    
    jtblUlogovaniKorisnici.getColumn("ID").setMinWidth(100);
    jtblUlogovaniKorisnici.getColumn("Ime i prezime").setMinWidth(400);
    jtblUlogovaniKorisnici.getColumn("Korisničko ime").setMinWidth(100);
    jtblUlogovaniKorisnici.getColumn("Datum zaposlenja").setMinWidth(150);
       
    JTableHeader header = jtblUlogovaniKorisnici.getTableHeader();
    header.setPreferredSize(new Dimension(100, 35));
}

    private void srediPrikaz() {
        
        jbtnZaustaviServer.setVisible(false);
        this.setLocationRelativeTo(null);
        //this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
    
     public ModelTabeleProdavci vratiTabeluProdavaca() {
        return (ModelTabeleProdavci) jtblUlogovaniKorisnici.getModel();
    }
}