/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Ljubimac;
import domen.Musterija;
import domen.Prodavac;
import domen.Racun;
import domen.StavkaRacuna;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import komunikacija.Komunikacija;
import logic.Kontroler;
import model.ModelTabeleLjubimciZaRacun;
import model.ModelTabeleStavkeRacuna;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormaKreirajRacun extends javax.swing.JFrame {
    private Racun racunZaIzmenu;
    private boolean izmenaMod = false;
    /**
     * Creates new form FormaPretragaClana
     */
    private List<Ljubimac> listaSvihLjubimaca;
    private ModelTabeleLjubimciZaRacun modelLjubimci;
    private ModelTabeleStavkeRacuna modelStavke;
    
    public FormaKreirajRacun() {
        initComponents();
        srediFormu();
        popuniComboProdavce();
        popuniComboMusterije();
        ucitajLjubimce();
        this.izmenaMod = false;
    }
    
        public FormaKreirajRacun(Racun racun) {
        this.racunZaIzmenu = racun;
        this.izmenaMod = true;
        initComponents();
        srediFormu();
        popuniComboProdavce();
        popuniComboMusterije();
        ucitajLjubimce();
        popuniPodatkeZaIzmenu(); // Popuni formu podacima iz računa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNaslov = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        jlblDatumZaduzenja = new javax.swing.JLabel();
        jlblDatumVracanja = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jbtnDodaj = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblLjubimci = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jbtnOdustani = new javax.swing.JButton();
        jlblZadID = new javax.swing.JLabel();
        jtxtPretraga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtnPretrazi1 = new javax.swing.JButton();
        jComboProdavac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboMusterija = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtDatum = new javax.swing.JTextField();
        jtxtPopust = new javax.swing.JTextField();
        jtxtUkupno = new javax.swing.JTextField();
        jtxtZaUplatu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerKolicina = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos zaduzenja");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Musterija:");

        jLabelNaslov.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelNaslov.setText("Kreiraj račun:");

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblStavke);

        jlblDatumZaduzenja.setDisplayedMnemonic('U');
        jlblDatumZaduzenja.setForeground(new java.awt.Color(255, 0, 0));

        jlblDatumVracanja.setDisplayedMnemonic('U');
        jlblDatumVracanja.setForeground(new java.awt.Color(255, 0, 0));

        jbtnSacuvaj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnSacuvaj.setText("Sačuvaj račun");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnObrisiStavku.setText("Obriši stavku");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        jbtnDodaj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnDodaj.setText("Dodaj stavku");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jtblLjubimci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblLjubimci);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Izabrani ljubimac:");

        jbtnOdustani.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jtxtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPretragaKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Pretraži ljubimca :");

        jbtnPretrazi1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPretrazi1.setText("Pretraži");
        jbtnPretrazi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretrazi1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Prodavac:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Datum:");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Popust:");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Ukupno:");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Za uplatu:");

        jtxtZaUplatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtZaUplatuActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Kolicina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelNaslov))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jComboProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jComboMusterija, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jtxtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jtxtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jtxtZaUplatu, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jbtnPretrazi1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jlblDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jlblDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbtnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelNaslov)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboMusterija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtxtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtZaUplatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnPretrazi1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(jSpinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jlblDatumVracanja)
                .addGap(22, 22, 22)
                .addComponent(jlblDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        if (jComboMusterija.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Izaberite musteriju!");
        return;
    }
    
    if (modelStavke.getStavke().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Račun mora imati bar jednu stavku!");
        return;
    }
    
    Prodavac prodavac = (Prodavac) jComboProdavac.getSelectedItem();
    Musterija musterija = (Musterija) jComboMusterija.getSelectedItem();
    
    Racun racun;
    if (izmenaMod && racunZaIzmenu != null) {
        // Koristi postojeći račun za izmenu
        racun = racunZaIzmenu;
        racun.setProdavac(prodavac);
        racun.setMusterija(musterija);
    } else {
        // Kreiraj novi račun
        racun = new Racun();
        racun.setDatumIzdavanja(new Date());
        racun.setProdavac(prodavac);
        racun.setMusterija(musterija);
    }
    
    racun.setPopust(musterija.getTipMusterije().getPopust());
    racun.setUkupanIznos(modelStavke.getUkupanIznos());
    racun.setIznosSaPopustom(racun.getUkupanIznos() - (racun.getUkupanIznos() * racun.getPopust() / 100));
    racun.setStavke(modelStavke.getStavke());
    
    KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
    kzo.setOperacija(izmenaMod ? Operacije.PROMENI_RACUN : Operacije.KREIRAJ_RACUN);
    kzo.setObjekatOperacije(racun);
    
    try {
        Komunikacija.getInstanca().posalji(kzo);
        ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
        
        if (soo.isUspesno()) {
            JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    } catch (InterruptedException ex) {
        Logger.getLogger(FormaKreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        int red = jtblStavke.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite stavku iz tabele!");
            return;
        }
        
        modelStavke.obrisiStavku(red);
        izracunajUkupno();
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
int red = jtblLjubimci.getSelectedRow();
    if (red < 0) {
        JOptionPane.showMessageDialog(this, "Izaberite ljubimca iz tabele!");
        return;
    }
    
    Ljubimac l = modelLjubimci.vratiLjubimca(red);
    int kolicina = (Integer) jSpinnerKolicina.getValue();
    
    // Proveri da li već postoji stavka sa istim ljubimcem
    boolean postoji = false;
    for (StavkaRacuna s : modelStavke.getStavke()) {
        if (s.getLjubimac().getIdLjubimac() == l.getIdLjubimac()) {
            // Ako postoji, povećaj količinu
            int novaKolicina = s.getKolicina() + kolicina;
            s.setKolicina(novaKolicina);
            s.setIznos(novaKolicina * s.getCena());
            postoji = true;
            break;
        }
    }
    
    if (!postoji) {
        // Ako ne postoji, dodaj novu stavku
        StavkaRacuna stavka = new StavkaRacuna();
        stavka.setRb(modelStavke.getRowCount() + 1);
        stavka.setLjubimac(l);
        stavka.setKolicina(kolicina);
        stavka.setCena(l.getCena());
        stavka.setIznos(kolicina * l.getCena());
        
        modelStavke.dodajStavku(stavka);
    } else {
        // Ako je povećana količina, samo osveži tabelu
        modelStavke.fireTableDataChanged();
    }
    
    izracunajUkupno();
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        this.dispose();

    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void jtxtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPretragaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pretraziLjubimce();
        }
    }//GEN-LAST:event_jtxtPretragaKeyPressed

    private void jbtnPretrazi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretrazi1ActionPerformed
        pretraziLjubimce();
    }//GEN-LAST:event_jbtnPretrazi1ActionPerformed

    private void jtxtZaUplatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtZaUplatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtZaUplatuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Musterija> jComboMusterija;
    private javax.swing.JComboBox<Prodavac> jComboProdavac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNaslov;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerKolicina;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnPretrazi1;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JLabel jlblDatumVracanja;
    private javax.swing.JLabel jlblDatumZaduzenja;
    private javax.swing.JLabel jlblZadID;
    private javax.swing.JTable jtblLjubimci;
    private javax.swing.JTable jtblStavke;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtPopust;
    private javax.swing.JTextField jtxtPretraga;
    private javax.swing.JTextField jtxtUkupno;
    private javax.swing.JTextField jtxtZaUplatu;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
    this.setLocationRelativeTo(null);
    this.setSize(1000, 800);
    setTitle("Kreiraj racun"); 

    
    // Podešavanje tabela
    modelLjubimci = new ModelTabeleLjubimciZaRacun();
    jtblLjubimci.setModel(modelLjubimci);
    jtblLjubimci.setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    jtblLjubimci.getTableHeader().setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    
    modelStavke = new ModelTabeleStavkeRacuna();
    jtblStavke.setModel(modelStavke);
    jtblStavke.setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    jtblStavke.getTableHeader().setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    
    // Podešavanje spinnera
    SpinnerNumberModel model = new SpinnerNumberModel(1, 1, 100, 1);
    jSpinnerKolicina.setModel(model);
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    jtxtDatum.setText(sdf.format(new Date()));
    jtxtDatum.setEditable(false);
    jtxtDatum.setEnabled(false);
    
    jtxtPopust.setEditable(false);
    jtxtPopust.setEnabled(false);
    
    jtxtUkupno.setEditable(false);
    jtxtUkupno.setEnabled(false);
    
    jtxtZaUplatu.setEditable(false);
    jtxtZaUplatu.setEnabled(false);
}
    
    private void popuniComboProdavce() {
        jComboProdavac.removeAllItems();
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_PRODAVCE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                List<Prodavac> prodavci = (List<Prodavac>) soo.getObjekatOperacija();
                for (Prodavac p : prodavci) {
                    jComboProdavac.addItem(p);
                }
                
                // Ako je prodavac već prijavljen, selektuj ga
                Prodavac prijavljeni = Kontroler.getInstanca().getPrijavljeniProdavac();
                if (prijavljeni != null) {
                    jComboProdavac.setSelectedItem(prijavljeni);
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaKreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   private void popuniComboMusterije() {
    jComboMusterija.removeAllItems();
    
    KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
    kzo.setOperacija(Operacije.VRATI_SVE_MUSTERIJE);
    
    try {
        Komunikacija.getInstanca().posalji(kzo);
        ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
        
        if (soo.isUspesno()) {
            List<Musterija> musterije = (List<Musterija>) soo.getObjekatOperacija();
            for (Musterija m : musterije) {
                System.out.println("Musterija: " + m.getIme() + " " + m.getPrezime() 
                    + ", Tip: " + m.getTipMusterije().getNaziv() 
                    + ", Popust: " + m.getTipMusterije().getPopust());
                jComboMusterija.addItem(m);
            }
            
            jComboMusterija.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    izracunajUkupno();
                }
            });
        }
    } catch (InterruptedException ex) {
        Logger.getLogger(FormaKreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    private void ucitajLjubimce() {
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_LJUBIMCE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                listaSvihLjubimaca = (List<Ljubimac>) soo.getObjekatOperacija();
                modelLjubimci.postaviListu(listaSvihLjubimaca);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaKreirajRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pretraziLjubimce() {
        String kriterijum = jtxtPretraga.getText().trim();
        
        if (kriterijum.isEmpty()) {
            modelLjubimci.postaviListu(listaSvihLjubimaca);
            return;
        }
        
        List<Ljubimac> filtrirani = new ArrayList<>();
        for (Ljubimac l : listaSvihLjubimaca) {
            if (l.getNaziv().toLowerCase().contains(kriterijum.toLowerCase()) ||
                l.getKategorija().toLowerCase().contains(kriterijum.toLowerCase())) {
                filtrirani.add(l);
            }
        }
        modelLjubimci.postaviListu(filtrirani);
    }
    
    private void izracunajUkupno() {
    double ukupno = modelStavke.getUkupanIznos();
    jtxtUkupno.setText(String.format("%.2f", ukupno));
    
    if (jComboMusterija.getSelectedItem() != null) {
        Musterija m = (Musterija) jComboMusterija.getSelectedItem();
        double popust = m.getTipMusterije().getPopust();
        jtxtPopust.setText(String.format("%.1f", popust));
        
        double zaUplatu = ukupno * (1 - popust / 100);
        jtxtZaUplatu.setText(String.format("%.2f", zaUplatu));
    } else {
        jtxtPopust.setText("0.0");
        jtxtZaUplatu.setText(jtxtUkupno.getText());
    }
}
    
    private void popuniPodatkeZaIzmenu() {
    if (racunZaIzmenu == null) return;
    
    // Postavi vrednosti u combo box-ove
    jComboProdavac.setSelectedItem(racunZaIzmenu.getProdavac());
    jComboMusterija.setSelectedItem(racunZaIzmenu.getMusterija());
    
    // Postavi datum
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    jtxtDatum.setText(sdf.format(racunZaIzmenu.getDatumIzdavanja()));
    
    // Postavi stavke u tabelu 
    List<StavkaRacuna> stavke = racunZaIzmenu.getStavke();
    if (stavke != null) {
        modelStavke.postaviListu(stavke);
    } else {
        modelStavke.clear();
    }
    
    // Izračunaj ukupno
    izracunajUkupno();
    
    // Promeni naslov i dugmad
    jLabelNaslov.setText("Izmena računa");
    jbtnSacuvaj.setText("Sačuvaj izmene");
}

}
