/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.RadnaSmena;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;
/**
 *
 * @author PC
 */
public class FormaUbaciRadnuSmenu extends javax.swing.JFrame {

    /**
     * Creates new form FormaUbaciRadnuSmenu
     */
    public FormaUbaciRadnuSmenu() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblNaziv = new javax.swing.JLabel();
        jlblPocetak = new javax.swing.JLabel();
        jlblKraj = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtPocetak = new javax.swing.JTextField();
        jtxtKraj = new javax.swing.JTextField();
        jbtnOdustani = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Unos radne smene:");

        jlblNaziv.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblNaziv.setText("Naziv smene:");

        jlblPocetak.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblPocetak.setText("Vreme početka (HH:mm):");

        jlblKraj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblKraj.setText("Vreme završetka (HH:mm):");

        jbtnOdustani.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPocetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblKraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbtnOdustani)
                        .addGap(51, 51, 51)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNaziv)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPocetak))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblKraj))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOdustani)
                    .addComponent(jbtnSacuvaj))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
         String naziv = jtxtNaziv.getText().trim();
        String pocetak = jtxtPocetak.getText().trim();
        String kraj = jtxtKraj.getText().trim();
        
        RadnaSmena smena = izvrsiValidaciju(naziv, pocetak, kraj);
        
        if (smena != null) {
            KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
            kzo.setOperacija(Operacije.UBACI_RADNU_SMENU);
            kzo.setObjekatOperacije(smena);
            
            try {
                Komunikacija.getInstanca().posalji(kzo);
                ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
                
                if (soo.isUspesno()) {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
                    ocistiPolja();
                } else {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(FormaUbaciRadnuSmenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private RadnaSmena izvrsiValidaciju(String naziv, String pocetak, String kraj) {
        boolean ok = true;
        
        if (naziv.isEmpty()) {
            jlblNaziv.setText("Obavezno polje!");
            jtxtNaziv.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblNaziv.setText("");
            jtxtNaziv.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (pocetak.isEmpty()) {
            jlblPocetak.setText("Obavezno polje!");
            jtxtPocetak.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else if (!pocetak.matches("([01]?[0-9]|2[0-3]):[0-5][0-9]")) {
            jlblPocetak.setText("Format HH:MM (npr. 08:30)");
            jtxtPocetak.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblPocetak.setText("");
            jtxtPocetak.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (kraj.isEmpty()) {
            jlblKraj.setText("Obavezno polje!");
            jtxtKraj.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else if (!kraj.matches("([01]?[0-9]|2[0-3]):[0-5][0-9]")) {
            jlblKraj.setText("Format HH:MM (npr. 16:00)");
            jtxtKraj.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblKraj.setText("");
            jtxtKraj.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (ok) {
            RadnaSmena r = new RadnaSmena();
            r.setNaziv(naziv);
            r.setVremePocetka(pocetak);
            r.setVremeZavrsetka(kraj);
            return r;
        }
        return null;
    }
    
    private void ocistiPolja() {
        jtxtNaziv.setText("");
        jtxtPocetak.setText("");
        jtxtKraj.setText("");
        jlblNaziv.setText("");
        jlblPocetak.setText("");
        jlblKraj.setText("");
    }
    
    private void srediFormu() {
        setLocationRelativeTo(null);
        setSize(700, 400);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JLabel jlblKraj;
    private javax.swing.JLabel jlblNaziv;
    private javax.swing.JLabel jlblPocetak;
    private javax.swing.JTextField jtxtKraj;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtPocetak;
    // End of variables declaration//GEN-END:variables
}
