/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;


import domen.Musterija;
import domen.TipMusterije;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;



public class FormaUnosMusterije extends javax.swing.JFrame {

    /**
     * Creates new form FormaUnosClanaa
     */
    public FormaUnosMusterije() {
        initComponents();
        srediFormu();
        popuniComboTipove();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtIme = new javax.swing.JTextField();
        jLabelIme = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();
        jlblPrezime = new javax.swing.JLabel();
        jlblIme = new javax.swing.JLabel();
        jlblDatumRodjenja = new javax.swing.JLabel();
        jLabelNaslov = new javax.swing.JLabel();
        jlblTip = new javax.swing.JLabel();
        jlblTelefon = new javax.swing.JLabel();
        jtxtBrojTelefona = new javax.swing.JTextField();
        jComboTip = new javax.swing.JComboBox<>();
        jLabelID = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jbtnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos autora");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtxtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 136, 201, 28));

        jLabelIme.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelIme.setText("Ime:");
        getContentPane().add(jLabelIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 139, 207, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Prezime:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 185, 224, -1));
        getContentPane().add(jtxtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 182, 200, 28));
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 228, 200, 28));

        jlblEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblEmail.setText("Email:");
        getContentPane().add(jlblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 231, 270, -1));

        jbtnSacuvaj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 418, 95, -1));

        jlblPrezime.setDisplayedMnemonic('U');
        jlblPrezime.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlblPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 155, 201, -1));

        jlblIme.setDisplayedMnemonic('U');
        jlblIme.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlblIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 118, -1, -1));

        jlblDatumRodjenja.setDisplayedMnemonic('U');
        jlblDatumRodjenja.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jlblDatumRodjenja, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 348, 201, -1));

        jLabelNaslov.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelNaslov.setText("Unesite mušteriju:");
        getContentPane().add(jLabelNaslov, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 31, -1, -1));

        jlblTip.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblTip.setText("Tip mušterije:");
        getContentPane().add(jlblTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 324, 260, -1));

        jlblTelefon.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlblTelefon.setText("Broj telefona:");
        getContentPane().add(jlblTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 277, 260, -1));
        getContentPane().add(jtxtBrojTelefona, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 274, 200, 28));

        getContentPane().add(jComboTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 320, 200, 31));

        jLabelID.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelID.setText("ID:");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 93, 171, -1));
        getContentPane().add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 90, 201, 28));

        jbtnIzmeni.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 416, 95, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        
        String ime = jtxtIme.getText().trim();
        String prezime = jtxtPrezime.getText().trim();
        String email = jtxtEmail.getText().trim();
        String telefon = jtxtBrojTelefona.getText().trim();
        TipMusterije tip = (TipMusterije) jComboTip.getSelectedItem();

        Musterija musterija = izvrsiValidaciju(ime, prezime, email, telefon, tip);
        
        if (musterija != null) {
            KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
            kzo.setOperacija(Operacije.KREIRAJ_MUSTERIJU);
            kzo.setObjekatOperacije(musterija);
            
            try {
                Komunikacija.getInstanca().posalji(kzo);
                ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
                
                if (soo.isUspesno()) {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
                    ocistiPolja();
                } else {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(FormaUnosMusterije.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        

    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        {{{{{{{int id = Integer.parseInt(jtxtID.getText());
            String ime = jtxtIme.getText().trim();
            String prezime = jtxtPrezime.getText().trim();
            String email = jtxtEmail.getText().trim();
            String telefon = jtxtBrojTelefona.getText().trim();
            TipMusterije tip = (TipMusterije) jComboTip.getSelectedItem();

            Musterija musterija = izvrsiValidaciju(ime, prezime, email, telefon, tip);
            if (musterija != null) {
                musterija.setIdMusterija(id);

                KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
                kzo.setOperacija(Operacije.PROMENI_MUSTERIJU);
                kzo.setObjekatOperacije(musterija);

                try {
                    Komunikacija.getInstanca().posalji(kzo);
                    ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();

                    if (soo.isUspesno()) {
                        JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormaUnosMusterije.class.getName()).log(Level.SEVERE, null, ex);
                }}
        }        }        }        }        }        }        }    }//GEN-LAST:event_jbtnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<TipMusterije> jComboTip;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelNaslov;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JLabel jlblDatumRodjenja;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblIme;
    private javax.swing.JLabel jlblPrezime;
    private javax.swing.JLabel jlblTelefon;
    private javax.swing.JLabel jlblTip;
    private javax.swing.JTextField jtxtBrojTelefona;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtPrezime;
    // End of variables declaration//GEN-END:variables

  

 private Musterija izvrsiValidaciju(String ime, String prezime, String email, String telefon, TipMusterije tip) {
        boolean ok = true;
        
        if (ime.isEmpty()) {
            jlblIme.setText("Obavezno polje!");
            jtxtIme.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblIme.setText("");
            jtxtIme.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (prezime.isEmpty()) {
            jlblPrezime.setText("Obavezno polje!");
            jtxtPrezime.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblPrezime.setText("");
            jtxtPrezime.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (email.isEmpty()) {
            jlblEmail.setText("Obavezno polje!");
            jtxtEmail.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else if (!email.contains("@")) {
            jlblEmail.setText("Email mora sadržati @!");
            jtxtEmail.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblEmail.setText("");
            jtxtEmail.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (telefon.isEmpty()) {
            jlblTelefon.setText("Obavezno polje!");
            jtxtBrojTelefona.setBorder(new LineBorder(Color.RED, 2));
            ok = false;
        } else {
            jlblTelefon.setText("");
            jtxtBrojTelefona.setBorder(new LineBorder(Color.GRAY, 1));
        }
        
        if (tip == null) {
            jlblTip.setText("Izaberite tip!");
            ok = false;
        } else {
            jlblTip.setText("");
        }
        
        if (ok) {
            Musterija m = new Musterija();
            m.setIme(ime);
            m.setPrezime(prezime);
            m.setEmail(email);
            m.setBrojTelefona(telefon);
            m.setTipMusterije(tip);
            return m;
        }
        return null;
    }

 private void popuniComboTipove() {
        jComboTip.removeAllItems();
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_TIPOVE_MUSTERIJE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                List<TipMusterije> tipovi = (List<TipMusterije>) soo.getObjekatOperacija();
                for (TipMusterije t : tipovi) {
                    jComboTip.addItem(t);
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaUnosMusterije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ocistiPolja() {
    jtxtIme.setText("");
    jtxtPrezime.setText("");
    jtxtEmail.setText("");
    jtxtBrojTelefona.setText("");
    jComboTip.setSelectedIndex(0);
    
    // Resetuj labele za greške
    jlblIme.setText("");
    jlblPrezime.setText("");
    jlblEmail.setText("");
    jlblTelefon.setText("");
    jlblTip.setText("");
    
    // Resetuj border-e
    jtxtIme.setBorder(new LineBorder(Color.GRAY, 1));
    jtxtPrezime.setBorder(new LineBorder(Color.GRAY, 1));
    jtxtEmail.setBorder(new LineBorder(Color.GRAY, 1));
    jtxtBrojTelefona.setBorder(new LineBorder(Color.GRAY, 1));
}

    private void srediFormu() {
    jLabelID.setVisible(false);
    jtxtID.setVisible(false);
    jbtnIzmeni.setVisible(false);   
    jbtnSacuvaj.setVisible(true);    
    this.setLocationRelativeTo(null);
    setTitle("Unos musterije"); 
}

   public void postaviVidljivoIzmeni() {
    jLabelID.setVisible(true);
    jtxtID.setVisible(true);
    jbtnSacuvaj.setVisible(false);   
    jbtnIzmeni.setVisible(true);     
    jLabelNaslov.setText("Izmenite musteriju:");
}

    public void postaviVrednostPoljima(Musterija m) {
        jtxtID.setText(String.valueOf(m.getIdMusterija()));
        jtxtIme.setText(m.getIme());
        jtxtPrezime.setText(m.getPrezime());
        jtxtEmail.setText(m.getEmail());
        jtxtBrojTelefona.setText(m.getBrojTelefona());
        jComboTip.setSelectedItem(m.getTipMusterije());
    }
}
