/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Musterija;
import domen.TipMusterije;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.ModelTabeleMusterija;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;


public class FormaPretragaMusterije extends javax.swing.JFrame {

    private List<TipMusterije> listaTipova;
    private final TipMusterije SVI_TIPOVI = new TipMusterije(0, "Svi tipovi", 0);
    
    public FormaPretragaMusterije() {
        initComponents();
        srediFormu();
        srediTabelu();
        popuniComboTipove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPretraga = new javax.swing.JTextField();
        jbtnPretrazi = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblMusterije = new javax.swing.JTable();
        jComboTip = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jbtnPonisti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga članova");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Pretraži mušteriju:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 27, 165, -1));

        jtxtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPretragaKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtPretraga, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 61, 248, 32));

        jbtnPretrazi.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPretrazi.setText("Pretraži");
        jbtnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPretrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 60, 132, 32));

        jbtnObrisi.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnObrisi.setText("Obriši");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 457, 106, 42));

        jbtnIzmeni.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 457, 114, 42));

        jtblMusterije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblMusterije);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 179, 620, 236));

        getContentPane().add(jComboTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 148, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Tip mušterije:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 165, -1));

        jbtnPonisti.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPonisti.setText("Poništi pretragu");
        jbtnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonistiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPonisti, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 111, 156, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPretragaKeyPressed
       
    }//GEN-LAST:event_jtxtPretragaKeyPressed

    private void jbtnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziActionPerformed
          String kriterijum = jtxtPretraga.getText().trim();
          Object selectedItem = jComboTip.getSelectedItem();
          TipMusterije tip = null;

          // Ako je izabran tip (a ne "Svi tipovi")
          if (selectedItem instanceof TipMusterije) {
              tip = (TipMusterije) selectedItem;
          }
        
        Musterija m = new Musterija();
        m.setKriterijumPretrage(kriterijum);
        m.setTipMusterije(tip);
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.PRETRAZI_MUSTERIJU);
        kzo.setObjekatOperacije(m);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                List<Musterija> musterije = (List<Musterija>) soo.getObjekatOperacija();
                ModelTabeleMusterija model = (ModelTabeleMusterija) jtblMusterije.getModel();
                model.postaviListu(musterije);
                JOptionPane.showMessageDialog(this, "Sistem je našao musterije po zadatim kriterijumima.", 
                    "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaPretragaMusterije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPretraziActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblMusterije.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite musteriju iz tabele!");
            return;
        }
        
        ModelTabeleMusterija model = (ModelTabeleMusterija) jtblMusterije.getModel();
        Musterija m = model.vratiMusteriju(red);
        
        int odgovor = JOptionPane.showConfirmDialog(this, 
            "Da li ste sigurni da želite da obrišete musteriju " + m.getIme() + " " + m.getPrezime() + "?",
            "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        
        if (odgovor == JOptionPane.YES_OPTION) {
            KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
            kzo.setOperacija(Operacije.OBRISI_MUSTERIJU);
            kzo.setObjekatOperacije(m);
            
            try {
                Komunikacija.getInstanca().posalji(kzo);
                ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
                
                if (soo.isUspesno()) {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
                    model.obrisiMusteriju(m);
                } else {
                    JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(FormaPretragaMusterije.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        int red = jtblMusterije.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite musteriju iz tabele!");
            return;
        }
        
        ModelTabeleMusterija model = (ModelTabeleMusterija) jtblMusterije.getModel();
        Musterija m = model.vratiMusteriju(red);
        
        FormaUnosMusterije forma = new FormaUnosMusterije();
        forma.postaviVidljivoIzmeni();
        forma.postaviVrednostPoljima(m);
        forma.setVisible(true);
        
        dispose();
    

    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jbtnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonistiActionPerformed
        jtxtPretraga.setText("");
        jComboTip.setSelectedIndex(0); // "Svi tipovi"
    }//GEN-LAST:event_jbtnPonistiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> jComboTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPonisti;
    private javax.swing.JButton jbtnPretrazi;
    private javax.swing.JTable jtblMusterije;
    private javax.swing.JTextField jtxtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniComboTipove() {
        //jComboTip.removeAllItems();
        jComboTip.addItem(SVI_TIPOVI);
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_TIPOVE_MUSTERIJE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                listaTipova = (List<TipMusterije>) soo.getObjekatOperacija();
                for (TipMusterije t : listaTipova) {
                    jComboTip.addItem(t);
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaPretragaMusterije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void srediFormu() {
        setLocationRelativeTo(null);
        //setSize(900, 700);
        setTitle("Pretraga mušterije");

    }
    
    private void srediTabelu() {
        ModelTabeleMusterija model = new ModelTabeleMusterija();
        jtblMusterije.setModel(model);
        jtblMusterije.setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
        jtblMusterije.getTableHeader().setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    }
}


