/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Musterija;
import domen.Prodavac;
import domen.Racun;
import domen.StavkaRacuna;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.ModelTabeleRacuni;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;

public class FormaPretragaRacuna extends javax.swing.JFrame {

    /**
     * Creates new form FormaPretragaClana
     */
    private List<Prodavac> listaProdavaca;
    private List<Musterija> listaMusterija;
    private ModelTabeleRacuni modelRacuni;
    
   private final Prodavac SVI_PRODAVCI = new Prodavac();
    private final Musterija SVE_MUSTERIJE = new Musterija();

{
    // Inicijalizacija blok - izvršava se pre konstruktora
    SVI_PRODAVCI.setIme("Svi");
    SVI_PRODAVCI.setPrezime("prodavci");
    
    SVE_MUSTERIJE.setIme("Sve");
    SVE_MUSTERIJE.setPrezime("mušterije");
}

    public FormaPretragaRacuna() {
        initComponents();
        srediFormu();
        srediTabelu();
        popuniComboProdavce();
        popuniComboMusterije();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtIznos = new javax.swing.JTextField();
        jbtnIzmeni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRacuni = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboProdavac = new javax.swing.JComboBox<>();
        jComboMusterija = new javax.swing.JComboBox<>();
        jbtnPonisti = new javax.swing.JButton();
        jbtnPretrazi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga članova");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtIznos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtIznosKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtIznos, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 135, 271, 32));

        jbtnIzmeni.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 544, 132, 32));

        jtblRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblRacuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRacuniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRacuni);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, 824, 253));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Računi:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 234, 118, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Prodavac:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 118, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Mušterija:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 118, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Iznos za uplatu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, 138, -1));

        getContentPane().add(jComboProdavac, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 30, 271, -1));

        getContentPane().add(jComboMusterija, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 82, 271, -1));

        jbtnPonisti.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPonisti.setText("Poništi pretragu");
        jbtnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonistiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPonisti, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 185, 165, 32));

        jbtnPretrazi1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtnPretrazi1.setText("Pretraži");
        jbtnPretrazi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretrazi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPretrazi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 134, 132, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIznosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIznosKeyPressed
        
    }//GEN-LAST:event_jtxtIznosKeyPressed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
       int red = jtblRacuni.getSelectedRow();
    if (red < 0) {
        JOptionPane.showMessageDialog(this, "Izaberite račun za izmenu!");
        return;
    }
    
    Racun r = modelRacuni.vratiRacun(red);
    
    // Pošalji zahtev za učitavanje stavki ovog računa
    KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
    kzo.setOperacija(Operacije.VRATI_STAVKE_RACUNA);
    kzo.setObjekatOperacije(r.getIdRacun());
    
    try {
        Komunikacija.getInstanca().posalji(kzo);
        ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
        
        if (soo.isUspesno()) {
            List<StavkaRacuna> stavke = (List<StavkaRacuna>) soo.getObjekatOperacija();
            r.setStavke(stavke); // Postavi stavke u račun
            
            // Otvori formu za izmenu sa svim stavkama
            FormaKreirajRacun forma = new FormaKreirajRacun(r);
            forma.setTitle("Izmena računa");
            forma.setVisible(true);
            
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ne mogu da učitam stavke računa: " + soo.getPoruka(), 
                "Greška", JOptionPane.ERROR_MESSAGE);
        }
    } catch (InterruptedException ex) {
        Logger.getLogger(FormaPretragaRacuna.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jtblRacuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRacuniMouseClicked
     
    }//GEN-LAST:event_jtblRacuniMouseClicked

    private void jbtnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonistiActionPerformed
        jComboProdavac.setSelectedIndex(0); // "Svi prodavci"
        jComboMusterija.setSelectedIndex(0); // "Sve mušterije"
        jtxtIznos.setText("");
    }//GEN-LAST:event_jbtnPonistiActionPerformed

    private void jbtnPretrazi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretrazi1ActionPerformed
         Prodavac prodavac = null;
        Musterija musterija = null;
        String iznosStr = jtxtIznos.getText().trim();
        Double iznos = null;
        
        if (jComboProdavac.getSelectedIndex() > 0) {
            prodavac = (Prodavac) jComboProdavac.getSelectedItem();
        }
        
        if (jComboMusterija.getSelectedIndex() > 0) {
            musterija = (Musterija) jComboMusterija.getSelectedItem();
        }
        
        if (!iznosStr.isEmpty()) {
            try {
                iznos = Double.parseDouble(iznosStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Iznos mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        Racun r = new Racun();
        r.setProdavac(prodavac);
        r.setMusterija(musterija);
        r.setIznosSaPopustom(iznos != null ? iznos : 0);
        r.setKriterijumPretrage(iznosStr); 
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.PRETRAZI_RACUN);
        kzo.setObjekatOperacije(r);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                List<Racun> racuni = (List<Racun>) soo.getObjekatOperacija();
                modelRacuni.postaviListu(racuni);
                if (racuni.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nema računa po zadatim kriterijumima.", 
                        "Informacija", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem je našao račune po zadatim kriterijumima.", 
                        "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaPretragaRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPretrazi1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Musterija> jComboMusterija;
    private javax.swing.JComboBox<Prodavac> jComboProdavac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnPonisti;
    private javax.swing.JButton jbtnPretrazi1;
    private javax.swing.JTable jtblRacuni;
    private javax.swing.JTextField jtxtIznos;
    // End of variables declaration//GEN-END:variables

    
    
     private void popuniComboProdavce() {
        jComboProdavac.removeAllItems();
        jComboProdavac.addItem(SVI_PRODAVCI);
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_PRODAVCE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                listaProdavaca = (List<Prodavac>) soo.getObjekatOperacija();
                for (Prodavac p : listaProdavaca) {
                    jComboProdavac.addItem(p);
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaPretragaRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void popuniComboMusterije() {
        jComboMusterija.removeAllItems();
        jComboMusterija.addItem(SVE_MUSTERIJE);
        
        KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
        kzo.setOperacija(Operacije.VRATI_SVE_MUSTERIJE);
        
        try {
            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();
            
            if (soo.isUspesno()) {
                listaMusterija = (List<Musterija>) soo.getObjekatOperacija();
                for (Musterija m : listaMusterija) {
                    jComboMusterija.addItem(m);
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(FormaPretragaRacuna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void srediFormu() {
        setLocationRelativeTo(null);
        //setSize(900, 700);
        setTitle("Pretraga računa"); 

    }
    
    private void srediTabelu() {
        modelRacuni = new ModelTabeleRacuni();
        jtblRacuni.setModel(modelRacuni);
        jtblRacuni.setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
        jtblRacuni.getTableHeader().setFont(new Font("Comic Sans MS", Font.PLAIN, 14));
    }

    
}


