/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.FontUIResource;
import komunikacija.Komunikacija;
import logic.Kontroler;
import operacije.Operacije;
import transfer.KlijentskiZahtevObjekat;
import transfer.ServerskiOdgovorObjekat;


public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form FGlavna
     */
    
    public GlavnaForma() {
        initComponents();
        
        srediFormu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblKorisnik = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMušterija = new javax.swing.JMenu();
        jmiUnosMusterije = new javax.swing.JMenuItem();
        jmiPretragaMusterije = new javax.swing.JMenuItem();
        jmRacun = new javax.swing.JMenu();
        jmiKreirajRacun = new javax.swing.JMenuItem();
        jmiPretragaRacuna = new javax.swing.JMenuItem();
        jmSifrarnici = new javax.swing.JMenu();
        jmiRadnaSmena = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiIzlogujSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlblKorisnik.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jCheckBox1.setText("jCheckBox1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(328, 30));
        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseMoved(evt);
            }
        });

        jmMušterija.setText("Mušterija");

        jmiUnosMusterije.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiUnosMusterije.setText("Unos mušterije");
        jmiUnosMusterije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosMusterijeActionPerformed(evt);
            }
        });
        jmMušterija.add(jmiUnosMusterije);

        jmiPretragaMusterije.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiPretragaMusterije.setText("Izmena/Brisanje mušterije");
        jmiPretragaMusterije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaMusterijeActionPerformed(evt);
            }
        });
        jmMušterija.add(jmiPretragaMusterije);

        jMenuBar1.add(jmMušterija);

        jmRacun.setText("Račun");

        jmiKreirajRacun.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiKreirajRacun.setText("Kreiraj račun");
        jmiKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajRacunActionPerformed(evt);
            }
        });
        jmRacun.add(jmiKreirajRacun);

        jmiPretragaRacuna.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiPretragaRacuna.setText(" Pretraga/izmena računa");
        jmiPretragaRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaRacunaActionPerformed(evt);
            }
        });
        jmRacun.add(jmiPretragaRacuna);

        jMenuBar1.add(jmRacun);

        jmSifrarnici.setText("Šifrarnici");

        jmiRadnaSmena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiRadnaSmena.setText("Radna smena");
        jmiRadnaSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRadnaSmenaActionPerformed(evt);
            }
        });
        jmSifrarnici.add(jmiRadnaSmena);

        jMenuBar1.add(jmSifrarnici);

        jMenu1.setText("Opcije");

        jmiIzlogujSe.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jmiIzlogujSe.setText("Izloguj se");
        jmiIzlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlogujSeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiIzlogujSe);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlblKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlblKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPretragaMusterijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaMusterijeActionPerformed
        FormaPretragaMusterije forma = new FormaPretragaMusterije();
    forma.setVisible(true);
    }//GEN-LAST:event_jmiPretragaMusterijeActionPerformed

    private void jmiIzlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlogujSeActionPerformed
        izlogujProdavca();
        System.exit(0);
    }//GEN-LAST:event_jmiIzlogujSeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        izlogujProdavca();
    }//GEN-LAST:event_formWindowClosing

    private void jmiKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajRacunActionPerformed
        FormaKreirajRacun forma=new FormaKreirajRacun();
        forma.setVisible(true);
}//GEN-LAST:event_jmiKreirajRacunActionPerformed

    private void jmiPretragaRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaRacunaActionPerformed
        FormaPretragaRacuna forma=new FormaPretragaRacuna();
        forma.setVisible(true);
        //test t=new test();
        //t.setVisible(true);
    }//GEN-LAST:event_jmiPretragaRacunaActionPerformed

    private void jmiUnosMusterijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosMusterijeActionPerformed
    FormaUnosMusterije forma = new FormaUnosMusterije();
        forma.setVisible(true);    }//GEN-LAST:event_jmiUnosMusterijeActionPerformed

    private void jMenuBar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseMoved
       
    }//GEN-LAST:event_jMenuBar1MouseMoved

    private void jmiRadnaSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRadnaSmenaActionPerformed
        FormaUbaciRadnuSmenu forma = new FormaUbaciRadnuSmenu();
    forma.setVisible(true);
                
    }//GEN-LAST:event_jmiRadnaSmenaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlblKorisnik;
    private javax.swing.JMenu jmMušterija;
    private javax.swing.JMenu jmRacun;
    private javax.swing.JMenu jmSifrarnici;
    private javax.swing.JMenuItem jmiIzlogujSe;
    private javax.swing.JMenuItem jmiKreirajRacun;
    private javax.swing.JMenuItem jmiPretragaMusterije;
    private javax.swing.JMenuItem jmiPretragaRacuna;
    private javax.swing.JMenuItem jmiRadnaSmena;
    private javax.swing.JMenuItem jmiUnosMusterije;
    // End of variables declaration//GEN-END:variables

    

    private void izlogujProdavca() {
        try {
            KlijentskiZahtevObjekat kzo = new KlijentskiZahtevObjekat();
            kzo.setObjekatOperacije(Kontroler.getInstanca().getPrijavljeniProdavac());
            kzo.setOperacija(Operacije.ODJAVA);

            Komunikacija.getInstanca().posalji(kzo);
            ServerskiOdgovorObjekat soo = Komunikacija.getInstanca().primi();

            if (soo.isUspesno()) {
                JOptionPane.showMessageDialog(this, soo.getPoruka(), "Uspešno!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, soo.getPoruka(), "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediFormu() {
        String ime = Kontroler.getInstanca().getPrijavljeniProdavac().getIme();
        String prezime = Kontroler.getInstanca().getPrijavljeniProdavac().getPrezime();
        String username = Kontroler.getInstanca().getPrijavljeniProdavac().getUsername();
        
        jlblKorisnik.setText("<html>Dobrodošli " + ime + " " + prezime + " (" + username + ")!<br>Izaberite odgovarajuću opciju.</html>");
        
        this.setLocationRelativeTo(null);
    }


   
}
